-- ============================================
-- SITES SEED DATA
-- 69 Sites from spreadsheet
-- ============================================

INSERT INTO sites (site_code, name, address, contact_name, email, phone) VALUES
('ARDBENNIE-DEPOT', 'Ardbennie Depot', 'Ardbennie, Harare', 'Godfrey Manyanga', 'ivy.magwede@redan.co.zw', '788817462'),
('ARDBENNIE-SS', 'Ardbennie SS', '38H Mitchel street Ardbennie, Harare', 'Luke Mudavangu', 'sallya.mangena@redan.co.zw', '788054838'),
('AVONDALE', 'Avondale', 'Corner Cliff Road and Lorojd Takawira Avenue, Avondale, Harare', 'Anesuishe Madzivanyanda', 'sallya.mangena@redan.co.zw', '774370640'),
('BEATRICE', 'Beatrice', 'Plot 25 Beatrice-Masvingo Highway, Beatrice', 'Tafadzwa Rukure', 'sallya.mangena@redan.co.zw', '779583201'),
('BEITBRIDGE', 'Beitbridge', 'Beitbridge', 'Purity Mushayamemba', 'tafara.ncube@redan.co.zw', '784520137'),
('BELLEVUE', 'Bellevue', '109 Gladstone Road, Bellevue, Bulawayo', 'Cleopatra Tapfuma', 'brendon.tembo@redan.co.zw', '779023597'),
('BELVEDERE', 'Belvedere', '18868 of 4833 Cnr Burton and Princesse Road, Belvedere, Harare', 'Isabella Jingura', 'tafara.ncube@redan.co.zw', '778549680'),
('BINDURA', 'Bindura', 'Bindura', 'McDonald', 'brendon.tembo@redan.co.zw', NULL),
('CHACHA', 'ChaCha', 'Chitungwiza', 'McDonald', 'brendon.tembo@redan.co.zw', NULL),
('CHIKWANHA', 'Chikwanha', '29 Gurba Township Seke, Chitungwiza', 'Daniah Makwasha', 'tafara.ncube@redan.co.zw', '788881340'),
('CHINHOYI', 'Chinhoyi', '31 Magamba Way Chinhoyi, Chinhoyi', 'Anorld Msiewa', 'tafara.ncube@redan.co.zw', '786091245'),
('CHIPINGE', 'Chipinge', '96 and 97 Main Street, Chipinge', 'Tariro Samanyara', 'tendai.mukamba@redan.co.zw', '785718160'),
('CHITUNGWIZA', 'Chitungwiza', 'Stand number 22199 Seke Township Chitungwiza, Harare', 'Naomi Makawa', 'tafara.ncube@redan.co.zw', '779503047'),
('CHIVHU', 'Chivhu', 'Stand 324 Corner Terylanche Street & Cloette street Chivhu, Chivhu', 'Albert Jecha', 'tafara.ncube@redan.co.zw', '774264292'),
('COLNE-VALLEY', 'Colne Valley', '718 Enterprise road, Colne Valley, Harare', 'Wiseman Muchokochoko', 'tafara.ncube@redan.co.zw', '773879596'),
('DABUKA-DEPOT', 'Dabuka Depot', 'Gweru', 'Arthur Mahochi', 'mandla.matshanda@redan.co.zw', '775653317'),
('DERBYSHIRE', 'Derbyshire', '633 Chitungwiza Road, Corner Derbyshire, Waterfalls, Harare', 'Tanatwa Fidze', 'tendai.mukamba@redan.co.zw', '779734509'),
('FIFE-STREET', 'Fife Street', '44 Fife Street, Bulawayo', 'Mthokozi Ndlovu', 'tafara.ncube@redan.co.zw', '779385974'),
('GAYSDON', 'Gaysdon', 'Corner Gaydon Road and Currick Creagh Road, Borrowdale, Harare', 'Knowledge Saguaya', 'tendai.mukamba@redan.co.zw', '782551027'),
('GLAUDINA', 'Glaudina', 'Std no. 37361 Merwede Township of Glaudina subdivision A, Harare', 'Mary Chasssa', 'sallya.mangena@redan.co.zw', '774408018'),
('GREENCROFT', 'Greencroft', '117 lomagundi road greencroft, Harare', 'Larneck Masona', 'sallya.mangena@redan.co.zw', '778546349'),
('GWERU', 'Gweru', 'Stand Number 121 & 122, Gwelo Township, Gweru', 'Yeukai Dowa', 'sallya.mangena@redan.co.zw', '779444881'),
('HAZICLIFFE', 'Hazicliffe', '1507 Hazicliffe Consortium, Domboshawa Road, Harare', 'Tafadzwa Shoko', 'tendai.mukamba@redan.co.zw', '775415694'),
('HAZLCLIFFE-1ST', 'Hazlcliffe 1st Street', 'Hazlcliffe first Street road, Harare', NULL, 'tendai.mukamba@redan.co.zw', NULL),
('HATFIELD', 'Hatfield', '66 Kili Winning Road, Hatfield, Harare', 'Tambudzai', 'brendon.tembo@redan.co.zw', '779677084'),
('HEADLANDS', 'Headlands', 'Stand number 7 headlands, Headlands', 'Moses Ziko', 'tendai.mukamba@redan.co.zw', '778971513'),
('KADOMA-CBD', 'Kadoma CBD', '45 Robert Mugabe Way Kadoma, Kadoma', 'Darlington Chirecha', 'sallya.mangena@redan.co.zw', '778567529'),
('KADOMA-HIGHWAY', 'Kadoma Highway', '3384 J, Tsongarai, Kadoma', 'Prosper Chipunza', 'sallya.mangena@redan.co.zw', '773285052'),
('KARIBA', 'Kariba', '5600 Batonga Tship Kariba, Kariba', 'Shaulin', 'brendon.tembo@redan.co.zw', NULL),
('KAROI-TRUCK', 'Karoi Truck Stop', 'Stand number 396 chirunda road hurungwe karoi, Karoi', 'Shadreck Mutenhwa', 'sallya.mangena@redan.co.zw', '785718193'),
('KWEKWE-ARMAN', 'Kwekwe Arman', '8430 Amaveni Road, Kwekwe', 'Nadia Ismail', 'sallya.mangena@redan.co.zw', '779391348'),
('LIBERATION-CITY', 'Liberation City', '11776 Corner Golden Quarry and Kirkman Road, Warren Park, Harare', 'Rachel', 'sallya.mangena@redan.co.zw', '774974916'),
('LOBENGULA-STREET', 'Lobengula Street', 'Corner 6th street and Lobengula, Bulawayo', 'Ayanda Ncube', 'tafara.ncube@redan.co.zw', NULL),
('LUVEVE', 'Luveve', '1243 Huggins road Luveve Bulawayo, Bulawayo', 'Troncitha C Kutita', 'brendon.tembo@redan.co.zw', '787120843'),
('MAKOKOBO', 'Makokobo', '6th Avenue extension, 28 Woodstock Road Thorngroove, Bulawayo', 'Amandlenkosi Sibanda', 'brendon.tembo@redan.co.zw', '787518164'),
('MANDAVA', 'Mandava', 'Stand number 80 Mandava, Zvishavane', 'Silina Khan', 'sallya.mangena@redan.co.zw', '779449816'),
('MASVINGO-CIPSHAM', 'Masvingo Cipsham', '2418 Cipsham Plots, Masvingo', 'Clemencia Katakura', 'sallya.mangena@redan.co.zw', '786195986'),
('MASVINGO-PANGOLIN', 'Masvingo Pangolin', '27451 Mushambike Drive Pangolin Masvingo, Masvingo', 'Nyasha Murezia', 'sallya.mangena@redan.co.zw', '778745243'),
('MAZOWE', 'Mazowe', 'MAZOWE WALK SHOPPING CENTRE STAND NO 124 MAZOWE T, Mazowe', 'Rodney Muchongagachera', 'sallya.mangena@redan.co.zw', '773488848'),
('MBARE', 'Mbare', '20067 Ardbennie road Mbare, Harare', 'Kudakwashe Mhachapiri', 'sallya.mangena@redan.co.zw', '779056940'),
('MOUNT-DARWIN', 'Mount Darwin', '188 Corner CMED Road, Mt Darwin', 'Mitchel Name', 'tendai.mukamba@redan.co.zw', '778431285'),
('MOUNT-PLEASANT', 'Mount Pleasant', '46A Corner Rise, Bond Street, Bond Shopping centre, MT Pleasant, Harare', 'Simbarashe Mutsago', 'sallya.mangena@redan.co.zw', '779673610'),
('MSSA', 'MSSA', '100-102 Mutare Road, Beverly Mass, Harare', 'David Mutuanchishiri', 'sallya.mangena@redan.co.zw', '779673610'),
('MURCHIWA', 'Murchiwa', 'Corner Simbaraseni Road and Eidon Shirtage, Harare', 'kasalilimi Kusena', 'sallya.mangena@redan.co.zw', '778543905'),
('MUTARE-FLYOVER', 'Mutare Flyover', '5029 Chimanimani Road, Mutare', 'Richard Mujaji', 'tendai.mukamba@redan.co.zw', '773611560'),
('MUTOKO', 'Mutoko', '413 Chinzanga Mutoko Centre, Mutoko', 'Tashinga Matsika', 'tafara.ncube@redan.co.zw', '779297102'),
('MVURWI', 'Mvurwi', '27/28 Chatham Avenue Mvurwi, Mvurwi', 'Catherine Nhoro', 'tendai.mukamba@redan.co.zw', '778927036'),
('NEMBUDZIYA', 'Nembudziya', 'Nembudziya Mission, Box 1005 Nembudziya, Gokwe', 'Euasha Chiilo', 'sallya.mangena@redan.co.zw', '712255634'),
('NEMO', 'Nemo', '21565 CITY north Shopping Mall, Harare', 'Kudaisy Muvandiwandiya', 'sallya.mangena@redan.co.zw', '774055007'),
('NYAMAHOBOGO', 'Nyamahobogo', 'Stand number 28 Nyamahobogo Business Centre Chosa Mt Darwin, Mt Darwin', 'Tracey Chikweshe', 'tendai.mukamba@redan.co.zw', NULL),
('NYIKA', 'Nyika', '631 Nyika Dustburg, Nyika Growth Point, Masvingo', 'Linda Mashate', 'sallya.mangena@redan.co.zw', '781672659'),
('NZVIMBO', 'Nzvimbo', 'Ruyamuro Nzvimbo Chiweshe, Chiweshe', 'Primadonna Linda', 'sallya.mangena@redan.co.zw', '776613895'),
('OK-MART', 'OK Mart', 'Ok Mart, Chiremba Road, Harare', 'Marlyne Tanyanyiwa', 'ivy.magwede@redan.co.zw', '777441850'),
('POMONA', 'Pomona', 'Stand number 455 Vainona Tship of stand No 318 Vainona Tship Harare, Harare', 'Marlyne Tanyanyiwa', 'sallya.mangena@redan.co.zw', '779022538'),
('RUSAPE', 'Rusape', '8324 Rusape, Rusape', 'Temptcion Dotito', 'sallya.mangena@redan.co.zw', '771227705'),
('RUWA-MAVAMBO', 'Ruwa Mavambo', 'Stand No 2974 Upfront Road, Ruwa, Harare', 'Obey Magudubi', 'sallya.mangena@redan.co.zw', '718778858'),
('SEKE', 'Seke', 'Harare', NULL, 'tafara.ncube@redan.co.zw', NULL),
('SECOND-STREET', 'Second Street', '77 Kwameh Nkuruma Street, Harare', 'MacDonald Mazorordze', 'tendai.mukamba@redan.co.zw', '786879340'),
('SEVENTH-STREET', 'Seventh Street', '159 Simons Machel Ave Harare, Harare', 'Kudaci Murhali Mushonga', 'tendai.mukamba@redan.co.zw', '779661507'),
('SKYWAY', 'Skyway', 'Stand no.169448, Corner Airport road and Cripps Road, Harare', 'Daniela Nyamhure', 'sallya.mangena@redan.co.zw', '772285106'),
('SOUTHSIDE', 'Southside', '143 Main street, Bulawayo', 'Simbarashe mangezi', 'brendon.tembo@redan.co.zw', '778006986'),
('TRIANGLE', 'Triangle', 'Corner Tanganda Nguiidu and Hockey Road, Triangle', 'Marshal Mataga', 'tafara.ncube@redan.co.zw', '774991556'),
('UMWINSIDALE', 'Umwinsidale', '2 Chishawasha Road, Umwinsidale, Harare', 'Faith Simango', 'sallya.mangena@redan.co.zw', '772425642'),
('WARREN-HILLS', 'Warren Hills', 'Harare', NULL, NULL, NULL),
('WESGATE', 'Wesgate', 'Westgate Complex Along Lomagundi after Roundabout, Harare', 'Molly Mutumwi', 'sallya.mangena@redan.co.zw', '778726532'),
('WORKINGTON', 'Workington', '32 Paisley Road, Workington, Harare', 'Sunay Naiir', 'mandla.statshanda@redan.co.zw', '773167213'),
('ZIMPLATS-DEPOT', 'Zimplats Depot', 'Ngezi', NULL, NULL, NULL),
('ZINDOGA', 'Zindoga', '11 malvern shopping centre Simon mazorodze waterfalls, Harare', 'Nicole Senga', 'sallya.mangena@redan.co.zw', '778481972'),
('ZVISHAVANE', 'Zvishavane', '82 Robert Mugabe Way, Zvishavane', 'Amandlenkosi Sibanda', 'sallya.mangena@redan.co.zw', '779051686')

ON CONFLICT (site_code) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    contact_name = EXCLUDED.contact_name,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone;

-- Verify insert
SELECT COUNT(*) as total_sites FROM sites;
